### PR TITLE
Remove updatemodel!

### PR DESCRIPTION
**Pull request by joehuchette**
Unfortunately I'm not sure how to deprecate this...

@mlubin @IainNZ

### CODE REVIEW

**Comment by joehuchette** [comment]
ref https://github.com/JuliaOpt/CPLEX.jl/issues/50

**Comment by mlubin** [comment]
Well, the first step is to make sure Gurobi works when ``updatemodel!`` isn't called.

**Comment by joehuchette** [comment]
...after we've decided this is something we actually want to do

**Comment by mlubin** [comment]
No objections here

**Comment by joehuchette** [comment]
Gurobi.jl works as-is with this. Objections to merging? Is it worth creating a v0.4 branch beforehand?

**Comment by mlubin** [comment]
Doesn't this break JuMP [here](https://github.com/JuliaOpt/JuMP.jl/blob/6ce3cd5ad7908cf8e98be5e771430e07d6b74675/src/solvers.jl#L426)?

**Comment by joehuchette** [comment]
Yes, it needs https://github.com/JuliaOpt/JuMP.jl/pull/708, which essentially just removes that block.

It works without breaking essentially by moving ``updatemodel!(::GurobiMathProgModel)`` from ``MathProgBase`` to the ``Gurobi`` module, and by not calling ``updatemodel!`` in ``buildInternalModel`` in JuMP. Somewhat sketchy, but seems to work fine.

**Comment by mlubin** [comment]
So we need to merge https://github.com/JuliaOpt/JuMP.jl/pull/708 and tag JuMP first. Even though this is breaking I'm not sure it's worth the 0.5 tag since that involves touching all solver packages. Let's just do it the slow way and hold off on merging this untill the next JuMP release?

**Comment by mlubin** [comment]
Or merge this but leave the ``updatemodel!`` stub so that it doesn't break the current JuMP releases

**Comment by joehuchette** [comment]
This really doesn't do much besides remove the ``updatemodel!`` stub (and a bunch of whitespace changes that crept in).

**Comment by mlubin** [comment]
The doc updates and the test updates are useful, at least CPLEX will start passing

**Comment by mlubin** [comment]
@joehuchette, any reason not to merge now this since we're about to do a new 0.x release of MPB?

**Comment by joehuchette** [comment]
Nope.

**Comment by madanim** [comment]
@joehuchette  @mlubin 
N.B. Removing updatemodel! seems to cause a fatal complain when cplex is called to solve a model ( e.g. 'solve(m)'  etc). It seems this makes the respective last releases (MPB/CPLEX.jl) not usable 'as is' together. Can you reproduce the issue ? Is there a plan to rather modify CPLEX.jl ?

**Comment by mlubin** [comment]
Yes, things are not in a coherent state right now. Hoping to resolve today
or tomorrow.

**Comment by mlubin** [comment]
@madanim MathProgBase master/0.5.0 should be working with JuMP master at this point

**Pull request merged**
