### PR TITLE
pull in code from NLP.jl

### PR DESCRIPTION
**Pull request by mlubin**
@dpo @tkelman 
This PR copies in the code from NLP.jl so that we can proceed with dpo/ampl.jl#6.

### CODE REVIEW

**Comment by dpo** [comment]
@abelsiqueira

**Comment by abelsiqueira** [comment]
PR looks good.

I just finished reading everything related, and I wasn't following the discussion, so correct me if I'm wrong:

  - NLP.jl code will go to MathProgBase.jl
  - ampl.jl and CUTEst.jl will use MathProgBase.jl instead of NLP.jl
  - ampl.jl and CUTEst.jl will, eventually, join JuliaOpt

**Comment by mlubin** [comment]
@abelsiqueira, thanks for taking a look. We haven't discussed moving CUTEst.jl to JuliaOpt, but that's certainly possible. The main point missing from above is that I'd like to see if there's a way we can increase the interoperability between the "NLP.jl" style models and the MathProgBase nonlinear interface. I wrote a wrapper for ampl.jl to provide problems in MPB format. I haven't looked at CUTEst.jl to see if it would be difficult to do the same.

**Comment by tkelman** [comment]
It will be hard to bring CUTEst up to the portability and ease-of-install goals that most JuliaOpt packages try to maintain as long as the software architecture there remains generating Fortran code. Reading from sif and converting directly into the MathProgBase nonlinear expression tree format would be a lot more work but a much cleaner design long-term.

For now I think the immediate goal is to remove the need to depend on an unregistered package, so at least the Ampl-reader interface can move forward towards registering and better integration with other JuliaOpt packages.

**Pull request merged**
