### PR TITLE
Drop Julia < v1.0 + REQUIRE -> Project.toml + update doc

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by mlubin** [comment]
What's the plan for tagging MPB 0.8 with minimal disruption?

**Comment by blegat** [comment]
I was thinking of tagging MPB v0.7.8. It is consistent with what we did for JuMP: we dropped Julia v0.6 in the Project.toml of JuMP from v0.18.5 to JuMP v0.18.6

**Comment by mlubin** [comment]
JuMP 0.18.6 still has a REQUIRE file and passes tests on 0.6, in case we ever need to release a fix for 0.6/0.7.

**Comment by blegat** [comment]
The idea of dropping Julia v0.6 is to avoid forcing the solver to have a dependency on Compat for testing MPB (since they need to include files in the test folder of MPB which uses Compat). Maybe it is not worth the breaking.

**Comment by mlubin** [comment]
Compat seems like a pretty harmless test dependency for the moment.

**Comment by blegat** [comment]
You mentioned in the JuMP PR that that we need to have Project.toml to support Julia v1.2. Doesn't it mean that MPB should have a version with Project.toml for JuMP v0.18.6 to support Julia v1.2 since MPB is a dependency of JuMP v0.18.6?

**Comment by mlubin** [comment]
My PR description in https://github.com/JuliaOpt/JuMP.jl/pull/1975 wasn't very clear. Project.toml is required to *tag* the release. The fix for Julia 1.2 was actually https://github.com/JuliaOpt/JuMP.jl/commit/f67fecf0db559925a6a330dec5480762b4895cb2.

**Comment by blegat** [comment]
Ok got it, let's leave MPB as is then

**Pull request closed without merging**
