### PR TITLE
Add NLP tests that call opimize! a second time

### PR DESCRIPTION
**Pull request by davidanthoff**
See discussion in JuliaOpt/KNITRO.jl#31.

### CODE REVIEW

**Comment by mlubin** [comment]
Standardization by unit tests, I like it. Does Ipopt pass?

**Comment by davidanthoff** [comment]
Yes, Ipopt passes. Any other NLP solver we should test?

**Comment by mlubin** [comment]
NLopt maybe?

**Comment by davidanthoff** [comment]
NLopt also passes.

**Comment by mlubin** [comment]
Thanks!

**Pull request merged**
