### PR TITLE
new tests for nonconsecutive conic indices - caused mosek failures

### PR DESCRIPTION
**Pull request by chriscoey**
these tests should be added to MOI also - see https://github.com/JuliaOpt/MathOptInterface.jl/issues/167
conic solvers cannot assume consecutive indices in cones

### CODE REVIEW

**Comment by mlubin** [comment]
Haven't checked correctness but looks good. Do SCS and ECOS pass the appropriate new tests?
We need to bump a few MPB requirements and tag releases to get travis passing:
https://github.com/JuliaOpt/GLPKMathProgInterface.jl/pull/42

**Comment by blegat** [comment]
I have checked: CSDP, SDPA, SCS and ECOS pass the tests.

**Comment by mlubin** [comment]
Ok, let's get travis passing before merging though.

**Comment by mlubin** [comment]
re: the travis failure, https://github.com/JuliaLang/METADATA.jl/pull/12026

**Pull request merged**
