### PR TITLE
fix and extend tests for conic duals

### PR DESCRIPTION
**Pull request by mlubin**
CC @madeleineudell @kaarthiksundar @IainNZ @joehuchette

### CODE REVIEW

**Comment by mlubin** [comment]
CC @ulfworsoe

**Comment by IainNZ** [comment]
Looks good on phone. I could have sworn we sanity checked the signs on these

**Comment by ulfworsoe** [comment]
Ok... I am probably misunderstanding something. What is your definition of
the dual sets?

Using the model from
http://mathprogbasejl.readthedocs.org/en/latest/conic.html

S = { x > 0 }, S* = { s > 0 }
S = { x < 0 }, S* = { s < 0 }
S = { x = 0 }, S* = { s unbounded }
S = { x1^2 < x2^2 + ... + xn^2 }, S* = { x < 0 } , S* = { s1^2 < s2^2 + ...
+ sn^2 }
S = Positive semidefinite, S* = Positive Semidefinite

Is this correct?

On Tue, Aug 11, 2015 at 3:20 PM, Iain Dunning <notifications@github.com>
wrote:

> Looks good on phone. I could have sworn we sanity checked the signs on
> these
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/MathProgBase.jl/pull/82#issuecomment-129870149>
> .
>



-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by mlubin** [comment]
@ulfworsoe, yes, NonNeg, NonPos, SOC, and SDP are self dual.

**Comment by ulfworsoe** [comment]
Now I am just being stupid. Doesn't this test
https://github.com/JuliaOpt/MathProgBase.jl/blob/master/test/conicinterface.jl#L206
check if the root of the dual SOC cone is negative?

On Tue, Aug 11, 2015 at 4:12 PM, Miles Lubin <notifications@github.com>
wrote:

> @ulfworsoe <https://github.com/ulfworsoe>, yes, NonNeg, NonPos, SOC, and
> SDP are self dual.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/MathProgBase.jl/pull/82#issuecomment-129896077>
> .
>



-- 
Ulf Worsøe
Mosek ApS

ulf.worsoe@mosek.com
www.mosek.com

**Comment by mlubin** [comment]
@ulfworsoe, yes, but that should be fixed in this PR

**Comment by mlubin** [comment]
Let me know if anyone finds something off here, otherwise I'll merge and tag so we can get to fixing the solvers.

**Comment by bodono** [comment]
:+1:

**Pull request merged**
