### PR TITLE
Remove requires

### PR DESCRIPTION
**Pull request by IainNZ**
Passes 0.4 JuMP tests, checking 0.3 tests. Don't see any problem with this right?

### CODE REVIEW

**Comment by IainNZ** [comment]
0.3 tests pass

**Comment by mlubin** [comment]
This should be fine

**Comment by IainNZ** [comment]
OK, will merge and tag.

**Comment by mlubin** [comment]
Thise were in there from when solver interfaces manually required files from MPB. I'd double check that there aren't any solvers that do this anymore.

**Comment by tkelman** [comment]
We don't have travis enabled here?

**Comment by IainNZ** [comment]
@mlubin haven't spotted anything from a quick check, but maybe I'm looking for wrong thing?

**Pull request merged**
