### PR TITLE
interface for updating conic RHS vec

### PR DESCRIPTION
**Pull request by mlubin**
Not sure about the name, but @ulfworsoe, how do you feel about this interface?

Ref https://github.com/JuliaOpt/Mosek.jl/issues/96

CC @chriscoey @madeleineudell

### CODE REVIEW

**Comment by ulfworsoe** [comment]
I would suggest, in addition to this, a function that could change a subset of indices, e.g.:
```
setbvec!(indices, values)
```
Perhaps a similar function to update a subset of rows in A:
```
setaelements!(indices, matrix)
```

**Comment by mlubin** [comment]
@ulfworsoe, are there cases where updating a subset of indices in the ``b`` vector would save any time relative to updating the whole vector? The solve time is at least O(n) where n is the dimension, so it seems hard to believe that a single pass through a vector could be a bottleneck.

We don't have an interface to update the ``A`` matrix mostly because we haven't needed it yet and the other conic solvers don't necessarily support this anyway.

**Comment by ulfworsoe** [comment]
@mlubin: Depends what you mean: Updating one term of the right-hand side would be O(1) in MOSEK, so updating n terms one at a time would be O(n). If you expect to always replace all or most of the terms, it is not relevant.

**Comment by mlubin** [comment]
@ulfworsoe: I mean that if you call ``setbvec!`` at most once in between solves with all the updates you would like to make, it can't possibly save a significant amount of time to use the sparse update instead of the dense update.

**Comment by ulfworsoe** [comment]
@mlubin: In that case it will make no difference.

**Comment by mlubin** [comment]
@ulfworsoe, given that we like to avoid providing multiple ways to do the same thing at the MPB level (which requires multiple implementations of the same thing for each solver interface), and that Mosek is the only solver that supports sparse updates of this form, I'd like to stick to the dense updates only at this point.

**Pull request merged**
