### PR TITLE
Introduce abstract over display output

### PR DESCRIPTION
**Pull request by odow**
This pull request introduces an abstraction over the quantity of output written to screen by solvers. It is intended to be used when solvers are embedded in higher level programs and the verbosity of their output is undesired.

See #117. @mlubin

### CODE REVIEW

**Comment by mlubin** [comment]
Devil's advocate here. Why not just use ``redirect_stdout`` to silence a solver?

@IainNZ @joehuchette @madeleineudell @JackDunnNZ @yeesian @dpo @ulfworsoe @ccoffrin

**Comment by odow** [comment]
Because I want to log info to the screen during the solve. It would be a hassle to redirect STDOUT, and then reset it everytime I wanted to print something (and then redirect it again).

**Comment by ccoffrin** [comment]
I am wondering, if there are going to be multiple parameter abstractions over all solvers, are a bunch of special named functions the way to go?

One possible design with more flexibility would be to have a generic method, like setMathProgBaseParameters(...), that has a syntax similar to the solver parameters but is defined over universal names for MathProgBase.

By default, if a solver ignores one of these parameters it throws a warning.  The way to avoid these warnings is to overload the default function with a mapping from the MathProgBase parameter names/units to the solver specific parameter names/units.

**Comment by mlubin** [comment]
No camelCase please :)

**Comment by mlubin** [comment]
I don't have a strong opinion, either having separate methods or having a single method for MPB parameters seems about the same to me.

**Comment by mlubin** [comment]
@ccoffrin, nobody seemed to excited about your proposal, so let's stick with the simpler way for now. These methods shouldn't be hard to deprecate if we decide to change the approach to parameters in the future.

**Pull request merged**
