### PR TITLE
Update quadprog.rst

### PR DESCRIPTION
**Pull request by EricForgy**
Not sure if it should be "columns" or if "a_i^Tx" should be "a_i x".

### CODE REVIEW

**Comment by mlubin** [comment]
The rows of A are ``a_i`` viewed as column vectors, or equivalently, the rows of A are ``a_i^T``.

**Comment by EricForgy** [comment]
Why not view a row as a row and drop the ^T? :)

In this way, the constraint equation becomes simply

A x sense b.

If I can remember how to edit a PR, I'll try again (after church) :)

**Comment by mlubin** [comment]
The constraint equation is already ``A x sense b``, we're just discussing how to write it down :)
From my background, ``a_i^Tx`` is unambiguously a dot product, while ``a_i x`` is more confusing. Vectors are almost always column oriented even when taken from rows of a matrix (again, from my experience). I agree though that it would help to clarify this. I'll update the docs.

**Comment by EricForgy** [comment]
Hehe. I agree. But the best way to write A x sense b is, I believe, .... A x sense b :)

**Comment by EricForgy** [comment]
I'm still getting familiar with github, but I tried submitting a new version that just says A x sense b, which I think is clear enough and less likely to confuse people (1 data point = I was confused :))

**Comment by mlubin** [comment]
Unfortunately ``Ax sense b`` is also pretty bizarre mathematically. I think the scalar version is more clear.

**Pull request closed without merging**
